In [1]:
import numpy as np

In [2]:
np.linalg.inv(np.array([
    [6, 5, -4],
    [-2, -1, 2],
    [4, 4, 0]
]))

array([[-1.  , -2.  ,  0.75],
       [ 1.  ,  2.  , -0.5 ],
       [-0.5 , -0.5 ,  0.5 ]])

In [16]:
import numpy as np

# Given matrix A
A = np.array([[2, 1, 1], [3, 2, 1], [2, 1, 2]])

# Calculate the inverse matrix B
B = np.linalg.inv(A)

# Calculate b11 + b22 + b33
result = B[0, 0] + B[1, 1] + B[2, 2]

print(result)


6.000000000000002


In [6]:
(1e30 + 1e15 - 1e30)

985162418487296.0

In [9]:
0 * np.inf

nan

In [15]:
1e30 + 1e10 - 1e30

0.0

In [20]:
import numpy as np

# Given matrix A
A = np.array([[1, 2, -3], [0, 1, 2], [0, 0, 1]])

# Calculate the inverse matrix B
B = np.linalg.inv(A)

# Calculate b11 + b22 + b33
result = B[0, 2]

print(B)


[[ 1. -2.  7.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]


In [22]:
import numpy as np

# Given matrix A
A = np.array([[1, 1, 1], [6, 5, 4], [13, 10, 8]])

# Calculate the inverse matrix B
B = np.linalg.inv(A)

# Calculate b11 + b22 + b33
result = B[0, 0] + B[1, 1] + B[2, 2]

print(B)

[[ 0. -2.  1.]
 [-4.  5. -2.]
 [ 5. -3.  1.]]


In [23]:
import numpy as np

# Given matrix A
A = np.array([[1, 0, 1], [0, 1, 1], [1, 1, 1]])

# Calculate the inverse matrix B
B = np.linalg.inv(A)

# Calculate b11 + b22 + b33
result = B[0, 0] + B[1, 1] + B[2, 2]

print(result)


-1.0
