In [1]:
import numpy as np

# Define a matrix
matrix = np.array([[1, 2],
                   [2, 4]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[0. 5.]

Eigenvectors:
[[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


In [2]:
# Define a matrix
matrix = np.array([[2, 1],
                   [0, -3]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[ 2. -3.]

Eigenvectors:
[[ 1.         -0.19611614]
 [ 0.          0.98058068]]


In [3]:
matrix = np.array([
    [4, -3, 1],
    [-1, 0, 5],
    [-1, 3, 2]
])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[ 3.  6. -3.]

Eigenvectors:
[[-0.81649658 -0.57735027 -0.40824829]
 [-0.40824829  0.57735027 -0.81649658]
 [-0.40824829  0.57735027  0.40824829]]


In [4]:
matrix = np.array([
    [1, 2],
    [0, 1]
])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[1. 1.]

Eigenvectors:
[[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  1.11022302e-16]]


In [5]:
matrix = np.array([
    [3, 0],
    [0, 3]
])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[3. 3.]

Eigenvectors:
[[1. 0.]
 [0. 1.]]


In [7]:
matrix = np.array([
    [-1, -1, 1],
    [0, -1, 0],
    [1, 1, -1]
])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[ 0. -2. -1.]

Eigenvectors:
[[ 0.70710678 -0.70710678 -0.57735027]
 [ 0.          0.          0.57735027]
 [ 0.70710678  0.70710678  0.57735027]]


In [8]:
matrix = np.array([
    [3, 1, 1],
    [-3, -1, -3],
    [1, 1, 3]
])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[2. 1. 2.]

Eigenvectors:
[[ 0.53452248  0.30151134 -0.70809946]
 [-0.80178373 -0.90453403  0.7061099 ]
 [ 0.26726124  0.30151134  0.00198956]]


In [9]:
matrix = np.array([
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1]
])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[ 0.00000000e+00  4.00000000e+00 -1.91800463e-34  0.00000000e+00]

Eigenvectors:
[[-0.8660254   0.5         0.86517865  0.8660254 ]
 [ 0.28867513  0.5        -0.25229548 -0.28867513]
 [ 0.28867513  0.5        -0.30644159 -0.28867513]
 [ 0.28867513  0.5        -0.30644159 -0.28867513]]


In [10]:
matrix = np.array([
    [1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1],

])

np.linalg.det(matrix)

0.0

In [11]:
matrix = np.array([
    [1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1],

])

np.linalg.det(matrix)

0.0