In [2]:
import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
matrix = np.array([
    [2, -1, 0, 0, -1, 0],
    [-1, 3, -1, 0, -1, 0],
    [0, -1, 2, -1, 0, 0],
    [0, 0, -1, 3, -1, -1],
    [-1, -1, 0, -1, 3, 0],
    [0, 0, 0, -1, 0, 1]
])

In [4]:
matrix

array([[ 2, -1,  0,  0, -1,  0],
       [-1,  3, -1,  0, -1,  0],
       [ 0, -1,  2, -1,  0,  0],
       [ 0,  0, -1,  3, -1, -1],
       [-1, -1,  0, -1,  3,  0],
       [ 0,  0,  0, -1,  0,  1]])

In [5]:
# take all eigenvectors by index 1
np.linalg.eig(matrix)[1]

array([[-0.40824829, -0.41486979, -0.50529469,  0.28867513, -0.56702343,
        -0.03232265],
       [-0.40824829, -0.30944167,  0.04026854,  0.28867513,  0.65812747,
        -0.46850031],
       [-0.40824829, -0.0692328 ,  0.75901025,  0.28867513, -0.20514371,
         0.35640753],
       [-0.40824829,  0.22093352,  0.20066454, -0.57735027, -0.30843449,
        -0.56195221],
       [-0.40824829, -0.22093352, -0.20066454, -0.57735027,  0.30843449,
         0.56195221],
       [-0.40824829,  0.79354426, -0.29398409,  0.28867513,  0.11403968,
         0.14441544]])

In [6]:
matrix = np.array([
    [2, -2, 0],
    [-2, 3, -1],
    [0, -1, 1]
])

In [7]:
np.linalg.eig(matrix)

(array([4.73205081e+00, 5.21609666e-17, 1.26794919e+00]),
 array([[-0.57735027, -0.57735027, -0.57735027],
        [ 0.78867513, -0.57735027, -0.21132487],
        [-0.21132487, -0.57735027,  0.78867513]]))

In [8]:
matrix = np.array([
    [3, -1, 0],
    [-1, 4, -1],
    [0, -1, 5]
])
np.linalg.eig(matrix)

(array([2.26794919, 4.        , 5.73205081]),
 array([[-0.78867513,  0.57735027,  0.21132487],
        [-0.57735027, -0.57735027, -0.57735027],
        [-0.21132487, -0.57735027,  0.78867513]]))

In [9]:
matrix = np.array([
    [3, -0.1, 0],
    [-0.1, 4, -0.1],
    [0, -0.1, 5]
])
np.linalg.eig(matrix)

(array([2.99004951, 4.        , 5.00995049]),
 array([[-0.99507377,  0.09901475,  0.00492623],
        [-0.09901475, -0.99014754, -0.09901475],
        [-0.00492623, -0.09901475,  0.99507377]]))

In [10]:
np.linalg.norm(matrix, ord=2)

5.009950493836207

In [11]:
matrix = np.array([
    [1, -1, -1],
    [-1, 3, -1],
    [-1, -1, 3]
])
np.linalg.eig(matrix)

(array([-2.22044605e-16,  3.00000000e+00,  4.00000000e+00]),
 array([[-8.16496581e-01, -5.77350269e-01, -1.33287903e-16],
        [-4.08248290e-01,  5.77350269e-01, -7.07106781e-01],
        [-4.08248290e-01,  5.77350269e-01,  7.07106781e-01]]))

In [18]:
#C2H6O
matrix = np.array([
    [1, -1, 0, 0, 0, 0, 0, 0, 0],
    [-1, 4, -1, -1, -1, 0, 0, 0, 0],
    [0, -1, 1, 0, 0, 0, 0, 0, 0],
    [0, -1, 0, 1, 0, 0, 0, 0, 0],
    [0, -1, 0, 0, 4, -1, -1, -1, 0],
    [0, 0, 0, 0, -1, 1, 0, 0, 0],
    [0, 0, 0, 0, -1, 0, 1, 0, 0],
    [0, 0, 0, 0, -1, 0, 0, 2, -1],
    [0, 0, 0, 0, 0, 0, 0, -1, 1]
])
np.linalg.eig(matrix)[1]

array([[ 1.37748471e-01,  2.03175364e-01,  5.03336041e-02,
        -3.33333333e-01,  3.73778264e-01,  1.40441056e-01,
         8.16496581e-01,  2.95583933e-01,  4.81847370e-01],
       [-6.44559684e-01, -6.27070595e-01, -6.91327632e-02,
        -3.33333333e-01,  2.68196958e-01,  5.92049341e-02,
        -4.74886867e-17, -1.48457248e-16, -1.35016587e-16],
       [ 1.37748471e-01,  2.03175364e-01,  5.03336041e-02,
        -3.33333333e-01,  3.73778264e-01,  1.40441056e-01,
        -4.08248290e-01, -7.96146163e-01, -5.84046009e-01],
       [ 1.37748471e-01,  2.03175364e-01,  5.03336041e-02,
        -3.33333333e-01,  3.73778264e-01,  1.40441056e-01,
        -4.08248290e-01,  5.00562231e-01,  1.02198639e-01],
       [ 6.69132151e-01, -5.55377582e-01, -2.63445859e-01,
        -3.33333333e-01, -1.24304670e-01, -2.18749680e-01,
        -1.00873627e-16, -2.09388543e-16, -7.33640816e-17],
       [-1.42999838e-01,  1.79946314e-01,  1.91807458e-01,
        -3.33333333e-01, -1.73239787e-01, -5.188999