In [1]:
import numpy as np

# Your matrix (replace this with your actual matrix)
matrix = np.array([
    [1, 1],
    [0, 1]
])

# Compute SVD
U, S, VT = np.linalg.svd(matrix)

print("U matrix:")
print(U)

print("\nS matrix (singular values):")
print(np.diag(S))

print("\nVT matrix:")
print(VT)


U matrix:
[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]

S matrix (singular values):
[[1.61803399 0.        ]
 [0.         0.61803399]]

VT matrix:
[[ 0.52573111  0.85065081]
 [-0.85065081  0.52573111]]


In [2]:
np.sqrt(2.618)

1.6180234856144702

In [3]:
# Your matrix (replace this with your actual matrix)
matrix = np.array([
    [0, 2],
    [-3, 0]
])

# Compute SVD
U, S, VT = np.linalg.svd(matrix)

print("U matrix:")
print(U)

print("\nS matrix (singular values):")
print(np.diag(S))

print("\nVT matrix:")
print(VT)

U matrix:
[[0. 1.]
 [1. 0.]]

S matrix (singular values):
[[3. 0.]
 [0. 2.]]

VT matrix:
[[-1. -0.]
 [ 0.  1.]]


In [4]:
# Your matrix (replace this with your actual matrix)
matrix = np.array([
    [-1, 0, 0],
    [0, 4, 0],
    [0, 0, -5]
])

# Compute SVD
U, S, VT = np.linalg.svd(matrix)

print("U matrix:")
print(U)

print("\nS matrix (singular values):")
print(np.diag(S))

print("\nVT matrix:")
print(VT)

U matrix:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

S matrix (singular values):
[[5. 0. 0.]
 [0. 4. 0.]
 [0. 0. 1.]]

VT matrix:
[[-0. -0. -1.]
 [ 0.  1.  0.]
 [-1. -0. -0.]]


In [5]:
# Your matrix (replace this with your actual matrix)
matrix = np.array([
    [2, 2],
    [2, 2]
])

# Compute SVD
U, S, VT = np.linalg.svd(matrix)

print("U matrix:")
print(U)

print("\nS matrix (singular values):")
print(np.diag(S))

print("\nVT matrix:")
print(VT)

U matrix:
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

S matrix (singular values):
[[4.0000000e+00 0.0000000e+00]
 [0.0000000e+00 6.7094089e-17]]

VT matrix:
[[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]


In [6]:
matrix11 = np.array([
    [1, 2],
    [3, 4]
])

In [7]:
matrix11_t = matrix11.T
matrix11_t

array([[1, 3],
       [2, 4]])

In [13]:
eig_11 = np.linalg.eigvals(np.dot(matrix11_t, matrix11))
eig_11

array([ 0.13393125, 29.86606875])

In [10]:
svd_11 = np.diag(np.linalg.svd(matrix11)[1])
svd_11

array([[5.4649857 , 0.        ],
       [0.        , 0.36596619]])

In [11]:
norm_2_11 = np.linalg.norm(matrix11, ord=2)
norm_2_11

5.464985704219043