In [1]:
import numpy as np

In [2]:
# write matrix by expanding horizontally
# matrix multiplication by np.dot()
A = np.array([[1, 2], [3, 4]])
B = np.array([[-4, 3], [-2, 1]])
x = np.array([[1], [2]])

In [3]:
# A Transpose
A.T

array([[1, 3],
       [2, 4]])

In [4]:
# A + B
A + B

array([[-3,  5],
       [ 1,  5]])

In [5]:
# A - B
A - B

array([[ 5, -1],
       [ 5,  3]])

In [6]:
# A * B
np.dot(A , B)

array([[ -8,   5],
       [-20,  13]])

In [7]:
# B * A
np.dot(B, A)

array([[5, 4],
       [1, 0]])

In [8]:
# A * x
np.dot(A, x)

array([[ 5],
       [11]])

In [9]:
# x Transpose * A
np.dot(x.T, A)

array([[ 7, 10]])

In [10]:
# x Transpose * A * x
np.dot(np.dot(x.T, A), x)

array([[27]])